# Generated by Django 6.1 on 2026-08-25 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], db_index=True, default='UPCOMING', max_length=15)),
                ('date', models.DateTimeField(blank=True, help_text='Leave blank for "date TBA" upcoming concerts.', null=True)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_concerts', to='studios_app.studio')),
            ],
            options={
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['status'], name='concerts_ap_status_2f433e_idx'), models.Index(fields=['date'], name='concerts_ap_date_1f28ec_idx'), models.Index(fields=['slug'], name='concerts_ap_slug_4994d5_idx')],
            },
        ),
    ]
