# Generated by Django 6.1 on 2026-08-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0002_concert_publish_at_concert_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='concerts/posters/'),
        ),
    ]
