# Generated by Django 6.1 on 2026-08-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0004_concert_cover_video_concert_cover_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='cover_video_url',
        ),
    ]
