# Generated by Django 6.1 on 2026-08-25 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_app', '0001_initial'),
        ('people_app', '0001_initial'),
        ('studios_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover_art_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='studios_app.studio')),
            ],
            options={
                'ordering': ('-release_date', 'title_ar'),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('lyrics', models.TextField(blank=True)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)])),
                ('song_type', models.CharField(choices=[('SINGLE', 'Single'), ('ALBUM_TRACK', 'Album Track'), ('MOVIE_THEME', 'Movie Theme'), ('SERIES_THEME', 'Series Theme'), ('COMMERCIAL_JINGLE', 'Commercial Jingle'), ('RELIGIOUS', 'Religious / Duaa')], db_index=True, max_length=20)),
                ('is_duet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music_app.album')),
                ('recording_studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_songs', to='studios_app.studio')),
                ('related_media', models.ForeignKey(blank=True, help_text='Set when the song was created specifically for a movie/series/commercial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_songs', to='media_app.media')),
            ],
            options={
                'ordering': ('-release_year', 'title_ar'),
            },
        ),
        migrations.CreateModel(
            name='SongCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SINGER', 'Singer'), ('LYRICIST', 'Lyricist / Poet'), ('COMPOSER', 'Composer'), ('ARRANGER', 'Arranger'), ('MUSIC_PRODUCER', 'Music Producer'), ('RECORDING_ENGINEER', 'Recording Engineer'), ('MIX_MASTER_ENGINEER', 'Mix & Master Engineer'), ('FEATURED_ARTIST', 'Featured Artist')], db_index=True, max_length=25)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_credits', to='people_app.person')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='music_app.song')),
            ],
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['release_date'], name='music_app_a_release_99a4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['release_year'], name='music_app_s_release_8680ab_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['song_type'], name='music_app_s_song_ty_ed160f_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['slug'], name='music_app_s_slug_827153_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='songcredit',
            unique_together={('song', 'person', 'role')},
        ),
    ]
