# Generated by Django 6.1 on 2026-08-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/covers/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-release_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='songs/covers/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/audio/')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music_app.album')),
            ],
            options={
                'ordering': ('-release_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SongCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SINGER', 'Singer'), ('COMPOSER', 'Composer'), ('LYRICIST', 'Lyricist'), ('ARRANGER', 'Arranger'), ('PRODUCER', 'Producer')], max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_credits', to='people_app.person')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='music_app.song')),
            ],
            options={
                'unique_together': {('song', 'person', 'role')},
            },
        ),
    ]
