# Generated by Django 6.1 on 2026-08-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_media_publish_at_media_visibility_and_more'),
        ('music_app', '0001_initial'),
        ('studios_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='When this becomes fully visible/open (used by Scheduled and Coming Soon).', null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='visibility',
            field=models.CharField(choices=[('DRAFT', 'Hidden (draft)'), ('SCHEDULED', 'Scheduled'), ('COMING_SOON', 'Coming Soon'), ('PUBLISHED', 'Published')], db_index=True, default='PUBLISHED', max_length=15),
        ),
        migrations.AddField(
            model_name='song',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='When this becomes fully visible/open (used by Scheduled and Coming Soon).', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='visibility',
            field=models.CharField(choices=[('DRAFT', 'Hidden (draft)'), ('SCHEDULED', 'Scheduled'), ('COMING_SOON', 'Coming Soon'), ('PUBLISHED', 'Published')], db_index=True, default='PUBLISHED', max_length=15),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['visibility'], name='music_app_a_visibil_84a36a_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['visibility'], name='music_app_s_visibil_32a266_idx'),
        ),
    ]
