# Generated by Django 6.1 on 2026-08-25 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_album_publish_at_album_visibility_song_publish_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='songs/covers/'),
        ),
        migrations.CreateModel(
            name='SongLyricSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('end_seconds', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('segment_type', models.CharField(choices=[('LYRICS', 'Lyrics'), ('MUSIC', 'Music (instrumental)'), ('SILENCE', 'Silence')], default='LYRICS', max_length=10)),
                ('text', models.TextField(blank=True, help_text='Required only when the segment type is Lyrics.')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_segments', to='music_app.song')),
            ],
            options={
                'ordering': ('start_seconds',),
                'indexes': [models.Index(fields=['song', 'start_seconds'], name='music_app_s_song_id_e8f56b_idx')],
            },
        ),
    ]
