# Generated by Django 6.1 on 2026-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_song_cover_image_songlyricsegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('ALBUM_TRACK', 'Album Track'), ('MOVIE_THEME', 'Movie Theme'), ('SERIES_THEME', 'Series Theme'), ('COMMERCIAL_JINGLE', 'Commercial Jingle'), ('RELIGIOUS', 'Religious / Duaa')], db_index=True, default='SINGLE', max_length=20),
        ),
    ]
