# Generated by Django 6.1 on 2026-08-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_album_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcredit',
            name='role',
            field=models.CharField(choices=[('SINGER', 'Singer'), ('LYRICIST', 'Lyricist / Poet'), ('COMPOSER', 'Composer'), ('ARRANGER', 'Arranger'), ('MUSIC_PRODUCER', 'Music Producer'), ('RECORDING_ENGINEER', 'Recording Engineer'), ('MIXING_ENGINEER', 'Mixing Engineer'), ('MASTERING_ENGINEER', 'Mastering Engineer'), ('MIX_MASTER_ENGINEER', 'Mix & Master Engineer'), ('FEATURED_ARTIST', 'Featured Artist')], db_index=True, max_length=25),
        ),
    ]
