# Generated by Django 6.1 on 2026-08-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0007_album_cover_video_album_cover_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_video_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='cover_video_url',
        ),
    ]
