# Generated by Django 6.1 on 2026-08-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0008_remove_album_cover_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/audio/'),
        ),
    ]
