# Generated by Django 6.1 on 2026-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0009_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_analysis_data',
            field=models.JSONField(blank=True, help_text='Detailed audio analysis data', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_bpm',
            field=models.FloatField(blank=True, help_text='Beats per minute', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_danceability',
            field=models.FloatField(blank=True, help_text='Danceability (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_energy',
            field=models.FloatField(blank=True, help_text='Energy level (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_key',
            field=models.CharField(blank=True, help_text='Musical key (e.g., C, Am, F#m)', max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_mood',
            field=models.CharField(blank=True, help_text='Mood of the song (e.g., happy, sad, energetic)', max_length=50),
        ),
    ]
