# Generated by Django 6.1 on 2026-08-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0008_remove_media_cover_video_url'),
        ('music_app', '0010_song_audio_analysis_data_song_audio_bpm_and_more'),
        ('studios_app', '0002_alter_studio_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, choices=[('UNSPECIFIED', 'غير محدد / Auto'), ('POP', 'Pop / بوب'), ('EGYPTIAN_POP', 'Egyptian Pop / بوب مصري'), ('ARABIC_POP', 'Arabic Pop / بوب عربي'), ('ORIENTAL_TARAB', 'Oriental & Tarab / شرقي وطربي'), ('RNB', 'R&B / آر أند بي'), ('BALLAD', 'Ballad / بالاد'), ('DANCE_ELECTRONIC', 'Dance / Electronic / دانس وإلكترونيك'), ('ACOUSTIC', 'Acoustic / أكوستيك'), ('SOFT_ROCK', 'Soft Rock / روك خفيف')], db_index=True, help_text='Musical genre', max_length=25),
        ),
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.CharField(blank=True, choices=[('UNSPECIFIED', 'غير محدد / Auto'), ('ROMANTIC', 'Romantic / رومانسي'), ('SAD_HEARTBREAK', 'Sad & Heartbreak / حزين / دراما / جرح'), ('ENERGETIC_UPBEAT', 'Energetic & Upbeat / حماسي / طاقة عالية / أفراح'), ('MOTIVATIONAL_HOPEFUL', 'Motivational & Hopeful / تحفيزي / أمل وتفاؤل'), ('CHILL_RELAXING', 'Chill & Relaxing / رايق / هادئ للاسترخاء'), ('NOSTALGIC', 'Nostalgic / ذكريات وحنين'), ('CONFIDENT_PLAYFUL', 'Confident & Playful / واثق / فريش')], db_index=True, help_text='Song mood/vibe', max_length=25),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre'], name='music_app_s_genre_e89018_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['mood'], name='music_app_s_mood_322bd6_idx'),
        ),
    ]
