# Generated by Django 6.1 on 2026-08-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0011_song_genre_song_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات التشغيل'),
        ),
    ]
