# Generated by Django 6.1 on 2026-09-01 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0012_song_play_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SingWithTamerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_type', models.CharField(choices=[('EVEN', 'Even (Zoji)'), ('ODD', 'Odd (Fardi)')], default='EVEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sing_projects', to='music_app.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sing_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LyricRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='lyric_recordings/')),
                ('duration_seconds', models.PositiveIntegerField(help_text='Recording duration in seconds')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('lyric_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='music_app.songlyricsegment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_recordings', to='music_app.singwithtamerproject')),
            ],
            options={
                'ordering': ('lyric_segment__start_seconds',),
            },
        ),
        migrations.AddIndex(
            model_name='singwithtamerproject',
            index=models.Index(fields=['user', 'song'], name='music_app_s_user_id_ebd201_idx'),
        ),
        migrations.AddIndex(
            model_name='singwithtamerproject',
            index=models.Index(fields=['is_completed'], name='music_app_s_is_comp_0c1575_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='singwithtamerproject',
            unique_together={('user', 'song', 'division_type')},
        ),
        migrations.AddIndex(
            model_name='lyricrecording',
            index=models.Index(fields=['project', 'lyric_segment'], name='music_app_l_project_96d76c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lyricrecording',
            unique_together={('project', 'lyric_segment')},
        ),
    ]
