# Generated by Django 6.1 on 2026-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0013_singwithtamerproject_lyricrecording_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singwithtamerproject',
            name='division_type',
            field=models.CharField(choices=[('EVEN', 'Tamer Starts'), ('ODD', 'You Start')], default='EVEN', max_length=10),
        ),
    ]
