# Generated by Django 6.1 on 2026-09-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0014_alter_singwithtamerproject_division_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlyricsegment',
            name='double_tracking',
            field=models.BooleanField(default=False, help_text='Enable double tracking effect for this segment'),
        ),
        migrations.AddField(
            model_name='songlyricsegment',
            name='vocal_doubling',
            field=models.BooleanField(default=False, help_text='Enable vocal doubling effect for this segment'),
        ),
    ]
