# Generated by Django 6.1 on 2026-09-02 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0015_songlyricsegment_double_tracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumental_file', models.FileField(blank=True, null=True, upload_to='instrumental_versions/')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='instrumental_versions/original/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('quality_score', models.FloatField(blank=True, help_text='Quality score of vocal removal (0.0 to 1.0)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumental_versions', to='music_app.song')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['song'], name='music_app_i_song_id_2f13e1_idx'), models.Index(fields=['status'], name='music_app_i_status_f095e8_idx')],
                'unique_together': {('song',)},
            },
        ),
    ]
