# Generated by Django 6.1 on 2026-09-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0016_instrumentalversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentalversion',
            name='instrumental_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='instrumental_versions/'),
        ),
        migrations.AlterField(
            model_name='instrumentalversion',
            name='original_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='instrumental_versions/original/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='songs/audio/'),
        ),
    ]
