# Generated by Django 6.1 on 2026-09-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0017_alter_instrumentalversion_instrumental_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentalversion',
            name='original_file',
        ),
    ]
