# Generated by Django 6.1 on 2026-09-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0018_remove_instrumentalversion_original_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='singwithtamerproject',
            name='final_audio_file',
            field=models.FileField(blank=True, help_text='The mixed duet (Tamer + user vocal). Private to the user, never a catalog Song.', max_length=500, null=True, upload_to='user_songs/'),
        ),
    ]
