# Generated by Django 6.1 on 2026-09-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0019_singwithtamerproject_final_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='singwithtamerproject',
            name='is_public',
            field=models.BooleanField(default=False, help_text='When on, the duet can be opened via its link by anyone, and a share option is shown.'),
        ),
    ]
