# Generated by Django 6.1 on 2026-09-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0020_singwithtamerproject_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='singwithtamerproject',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singwithtamerproject',
            name='processing_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20),
        ),
    ]
