# Generated by Django 6.1 on 2026-09-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0028_dailyguessattempt_listening_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlyricsegment',
            name='segment_type',
            field=models.CharField(choices=[('LYRICS', 'Lyrics'), ('MUSIC', 'Music (instrumental)'), ('SILENCE', 'Silence'), ('FULL_SONG', 'Full song lyrics')], default='LYRICS', max_length=10),
        ),
    ]
