# Generated by Django 6.1 on 2026-09-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0029_add_full_song_segment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='singwithtamerproject',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
