# Generated by Django 6.1 on 2026-09-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0030_singwithtamerproject_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='singwithtamerproject',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
