# Generated by Django 6.1 on 2026-09-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0031_singwithtamerproject_progress_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='singwithtamerproject',
            name='video_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singwithtamerproject',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='duet_videos/'),
        ),
        migrations.AddField(
            model_name='singwithtamerproject',
            name='video_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20),
        ),
    ]
