# Generated by Django 6.1 on 2026-09-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0032_singwithtamerproject_video_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singwithtamerproject',
            name='video_progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
