services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - tamerhosny_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./credentials/.env
    ports:
      - "5433:5432"

volumes:
  tamerhosny_postgres_data:
    external: true
