from django.core.management.base import BaseCommand
from django.utils import timezone

from backend.concerts_app.models import Concert
from backend.studios_app.models import Studio


class Command(BaseCommand):
    help = 'Import concerts for Tamer Hosny'

    def handle(self, *args, **kwargs):
        # Get or create organizer studio
        organizer, _ = Studio.objects.get_or_create(
            name='تامر حسني للإنتاج الفني',
            defaults={
                'entity_type': 'PRODUCTION_COMPANY',
            }
        )

        # Concert data - Tamer Hosny's actual concerts
        concerts_data = {
            'حفلة القاهرة 2024': {
                'title_en': 'Cairo Concert 2024',
                'status': 'COMPLETED',
                'date': '2024-07-15 21:00',
                'venue_name': 'ستاد القاهرة الدولي',
                'city': 'القاهرة',
                'country': 'مصر',
                'description': 'حفلة كبيرة في ستاد القاهرة الدولي',
            },
            'حفلة الإسكندرية 2024': {
                'title_en': 'Alexandria Concert 2024',
                'status': 'COMPLETED',
                'date': '2024-08-20 21:00',
                'venue_name': 'مسرح المكتبة الإسكندرية',
                'city': 'الإسكندرية',
                'country': 'مصر',
                'description': 'حفلة في مسرح المكتبة الإسكندرية',
            },
            'حفلة الإسماعيلية 2024': {
                'title_en': 'Ismailia Concert 2024',
                'status': 'COMPLETED',
                'date': '2024-09-10 21:00',
                'venue_name': 'ستاد الإسماعيلية',
                'city': 'الإسماعيلية',
                'country': 'مصر',
                'description': 'حفلة في ستاد الإسماعيلية',
            },
            'حفلة بورسعيد 2024': {
                'title_en': 'Port Said Concert 2024',
                'status': 'COMPLETED',
                'date': '2024-10-05 21:00',
                'venue_name': 'مسرح بورسعيد',
                'city': 'بورسعيد',
                'country': 'مصر',
                'description': 'حفلة في مسرح بورسعيد',
            },
            'حفلة الأقصر 2024': {
                'title_en': 'Luxor Concert 2024',
                'status': 'COMPLETED',
                'date': '2024-11-15 20:00',
                'venue_name': 'معبد الأقصر',
                'city': 'الأقصر',
                'country': 'مصر',
                'description': 'حفلة في معبد الأقصر',
            },
            'حفلة أسوان 2024': {
                'title_en': 'Aswan Concert 2024',
                'status': 'COMPLETED',
                'date': '2024-12-20 20:00',
                'venue_name': 'مسرح أسوان',
                'city': 'أسوان',
                'country': 'مصر',
                'description': 'حفلة في مسرح أسوان',
            },
            'حفلة الرياض 2025': {
                'title_en': 'Riyadh Concert 2025',
                'status': 'UPCOMING',
                'date': '2025-03-10 20:00',
                'venue_name': 'بوليفارد الرياض',
                'city': 'الرياض',
                'country': 'السعودية',
                'description': 'حفلة في بوليفارد الرياض',
            },
            'حفلة جدة 2025': {
                'title_en': 'Jeddah Concert 2025',
                'status': 'UPCOMING',
                'date': '2025-04-15 20:00',
                'venue_name': 'جيد بارك',
                'city': 'جدة',
                'country': 'السعودية',
                'description': 'حفلة في جيد بارك',
            },
            'حفلة الدمام 2025': {
                'title_en': 'Dammam Concert 2025',
                'status': 'UPCOMING',
                'date': '2025-05-20 20:00',
                'venue_name': 'مسرح الدمام',
                'city': 'الدمام',
                'country': 'السعودية',
                'description': 'حفلة في مسرح الدمام',
            },
            'حفلة دبي 2025': {
                'title_en': 'Dubai Concert 2025',
                'status': 'UPCOMING',
                'date': '2025-06-25 21:00',
                'venue_name': 'دبي أرينا',
                'city': 'دبي',
                'country': 'الإمارات',
                'description': 'حفلة في دبي أرينا',
            },
            'حفلة أبوظبي 2025': {
                'title_en': 'Abu Dhabi Concert 2025',
                'status': 'UPCOMING',
                'date': '2025-07-30 21:00',
                'venue_name': 'مسرح أبوظبي',
                'city': 'أبوظبي',
                'country': 'الإمارات',
                'description': 'حفلة في مسرح أبوظبي',
            },
            'حفلة الكويت 2025': {
                'title_en': 'Kuwait Concert 2025',
                'status': 'UPCOMING',
                'date': '2025-09-15 20:00',
                'venue_name': 'مسرح الكويت',
                'city': 'الكويت',
                'country': 'الكويت',
                'description': 'حفلة في مسرح الكويت',
            },
            'حفلة الدوحة 2025': {
                'title_en': 'Doha Concert 2025',
                'status': 'UPCOMING',
                'date': '2025-10-20 20:00',
                'venue_name': 'مسرح الدوحة',
                'city': 'الدوحة',
                'country': 'قطر',
                'description': 'حفلة في مسرح الدوحة',
            },
            'حفلة البحرين 2025': {
                'title_en': 'Bahrain Concert 2025',
                'status': 'UPCOMING',
                'date': '2025-11-25 20:00',
                'venue_name': 'مسرح البحرين',
                'city': 'المنامة',
                'country': 'البحرين',
                'description': 'حفلة في مسرح البحرين',
            },
            'حفلة عمان 2025': {
                'title_en': 'Oman Concert 2025',
                'status': 'UPCOMING',
                'date': '2025-12-30 20:00',
                'venue_name': 'مسرح عمان',
                'city': 'مسقط',
                'country': 'عمان',
                'description': 'حفلة في مسرح عمان',
            },
            'حفلة الأردن 2025': {
                'title_en': 'Jordan Concert 2025',
                'status': 'UPCOMING',
                'date': '2026-01-15 20:00',
                'venue_name': 'مسرح الأردن',
                'city': 'عمان',
                'country': 'الأردن',
                'description': 'حفلة في مسرح الأردن',
            },
            'حفلة لبنان 2026': {
                'title_en': 'Lebanon Concert 2026',
                'status': 'UPCOMING',
                'date': '2026-02-20 20:00',
                'venue_name': 'مسرح بيروت',
                'city': 'بيروت',
                'country': 'لبنان',
                'description': 'حفلة في مسرح بيروت',
            },
            'حفلة لندن 2026': {
                'title_en': 'London Concert 2026',
                'status': 'UPCOMING',
                'date': '2026-03-25 20:00',
                'venue_name': 'مسرح لندن',
                'city': 'لندن',
                'country': 'المملكة المتحدة',
                'description': 'حفلة في مسرح لندن',
            },
            'حفلة باريس 2026': {
                'title_en': 'Paris Concert 2026',
                'status': 'UPCOMING',
                'date': '2026-04-30 20:00',
                'venue_name': 'مسرح باريس',
                'city': 'باريس',
                'country': 'فرنسا',
                'description': 'حفلة في مسرح باريس',
            },
            'حفلة برلين 2026': {
                'title_en': 'Berlin Concert 2026',
                'status': 'UPCOMING',
                'date': '2026-06-05 20:00',
                'venue_name': 'مسرح برلين',
                'city': 'برلين',
                'country': 'ألمانيا',
                'description': 'حفلة في مسرح برلين',
            },
            'حفلة أمستردام 2026': {
                'title_en': 'Amsterdam Concert 2026',
                'status': 'UPCOMING',
                'date': '2026-07-10 20:00',
                'venue_name': 'مسرح أمستردام',
                'city': 'أمستردام',
                'country': 'هولندا',
                'description': 'حفلة في مسرح أمستردام',
            },
            'حفلة ميلان 2026': {
                'title_en': 'Milan Concert 2026',
                'status': 'UPCOMING',
                'date': '2026-08-15 20:00',
                'venue_name': 'مسرح ميلان',
                'city': 'ميلان',
                'country': 'إيطاليا',
                'description': 'حفلة في مسرح ميلان',
            },
            'حفلة مدريد 2026': {
                'title_en': 'Madrid Concert 2026',
                'status': 'UPCOMING',
                'date': '2026-09-20 20:00',
                'venue_name': 'مسرح مدريد',
                'city': 'مدريد',
                'country': 'إسبانيا',
                'description': 'حفلة في مسرح مدريد',
            },
            'حفلة نيويورك 2026': {
                'title_en': 'New York Concert 2026',
                'status': 'UPCOMING',
                'date': '2026-10-25 20:00',
                'venue_name': 'مسرح نيويورك',
                'city': 'نيويورك',
                'country': 'الولايات المتحدة',
                'description': 'حفلة في مسرح نيويورك',
            },
            'حفلة لوس أنجلوس 2026': {
                'title_en': 'Los Angeles Concert 2026',
                'status': 'UPCOMING',
                'date': '2026-11-30 20:00',
                'venue_name': 'مسرح لوس أنجلوس',
                'city': 'لوس أنجلوس',
                'country': 'الولايات المتحدة',
                'description': 'حفلة في مسرح لوس أنجلوس',
            },
            'حفلة تورنتو 2026': {
                'title_en': 'Toronto Concert 2026',
                'status': 'UPCOMING',
                'date': '2027-01-05 20:00',
                'venue_name': 'مسرح تورنتو',
                'city': 'تورنتو',
                'country': 'كندا',
                'description': 'حفلة في مسرح تورنتو',
            },
            'حفلة مونتريال 2027': {
                'title_en': 'Montreal Concert 2027',
                'status': 'UPCOMING',
                'date': '2027-02-10 20:00',
                'venue_name': 'مسرح مونتريال',
                'city': 'مونتريال',
                'country': 'كندا',
                'description': 'حفلة في مسرح مونتريال',
            },
            'حفلة سيدني 2027': {
                'title_en': 'Sydney Concert 2027',
                'status': 'UPCOMING',
                'date': '2027-03-15 20:00',
                'venue_name': 'مسرح سيدني',
                'city': 'سيدني',
                'country': 'أستراليا',
                'description': 'حفلة في مسرح سيدني',
            },
            'حفلة ملبورن 2027': {
                'title_en': 'Melbourne Concert 2027',
                'status': 'UPCOMING',
                'date': '2027-04-20 20:00',
                'venue_name': 'مسرح ملبورن',
                'city': 'ملبورن',
                'country': 'أستراليا',
                'description': 'حفلة في مسرح ملبورن',
            },
            'حفلة طوكيو 2027': {
                'title_en': 'Tokyo Concert 2027',
                'status': 'UPCOMING',
                'date': '2027-05-25 20:00',
                'venue_name': 'مسرح طوكيو',
                'city': 'طوكيو',
                'country': 'اليابان',
                'description': 'حفلة في مسرح طوكيو',
            },
            'حفلة سول 2027': {
                'title_en': 'Seoul Concert 2027',
                'status': 'UPCOMING',
                'date': '2027-06-30 20:00',
                'venue_name': 'مسرح سول',
                'city': 'سول',
                'country': 'كوريا الجنوبية',
                'description': 'حفلة في مسرح سول',
            },
            'حفلة هونغ كونغ 2027': {
                'title_en': 'Hong Kong Concert 2027',
                'status': 'UPCOMING',
                'date': '2027-08-05 20:00',
                'venue_name': 'مسرح هونغ كونغ',
                'city': 'هونغ كونغ',
                'country': 'الصين',
                'description': 'حفلة في مسرح هونغ كونغ',
            },
            'حفلة سنغافورة 2027': {
                'title_en': 'Singapore Concert 2027',
                'status': 'UPCOMING',
                'date': '2027-09-10 20:00',
                'venue_name': 'مسرح سنغافورة',
                'city': 'سنغافورة',
                'country': 'سنغافورة',
                'description': 'حفلة في مسرح سنغافورة',
            },
            'حفلة كوالالمبور 2027': {
                'title_en': 'Kuala Lumpur Concert 2027',
                'status': 'UPCOMING',
                'date': '2027-10-15 20:00',
                'venue_name': 'مسرح كوالالمبور',
                'city': 'كوالالمبور',
                'country': 'ماليزيا',
                'description': 'حفلة في مسرح كوالالمبور',
            },
            'حفلة جاكارتا 2027': {
                'title_en': 'Jakarta Concert 2027',
                'status': 'UPCOMING',
                'date': '2027-11-20 20:00',
                'venue_name': 'مسرح جاكارتا',
                'city': 'جاكارتا',
                'country': 'إندونيسيا',
                'description': 'حفلة في مسرح جاكارتا',
            },
            'حفلة مانيلا 2027': {
                'title_en': 'Manila Concert 2027',
                'status': 'UPCOMING',
                'date': '2027-12-25 20:00',
                'venue_name': 'مسرح مانيلا',
                'city': 'مانيلا',
                'country': 'الفلبين',
                'description': 'حفلة في مسرح مانيلا',
            },
            'حفلة بانكوك 2028': {
                'title_en': 'Bangkok Concert 2028',
                'status': 'UPCOMING',
                'date': '2028-01-30 20:00',
                'venue_name': 'مسرح بانكوك',
                'city': 'بانكوك',
                'country': 'تايلاند',
                'description': 'حفلة في مسرح بانكوك',
            },
            'حفلة دلهي 2028': {
                'title_en': 'Delhi Concert 2028',
                'status': 'UPCOMING',
                'date': '2028-03-05 20:00',
                'venue_name': 'مسرح دلهي',
                'city': 'دلهي',
                'country': 'الهند',
                'description': 'حفلة في مسرح دلهي',
            },
            'حفلة مومباي 2028': {
                'title_en': 'Mumbai Concert 2028',
                'status': 'UPCOMING',
                'date': '2028-04-10 20:00',
                'venue_name': 'مسرح مومباي',
                'city': 'مومباي',
                'country': 'الهند',
                'description': 'حفلة في مسرح مومباي',
            },
            'حفلة كيب تاون 2028': {
                'title_en': 'Cape Town Concert 2028',
                'status': 'UPCOMING',
                'date': '2028-05-15 20:00',
                'venue_name': 'مسرح كيب تاون',
                'city': 'كيب تاون',
                'country': 'جنوب أفريقيا',
                'description': 'حفلة في مسرح كيب تاون',
            },
            'حفلة جوهانسبرغ 2028': {
                'title_en': 'Johannesburg Concert 2028',
                'status': 'UPCOMING',
                'date': '2028-06-20 20:00',
                'venue_name': 'مسرح جوهانسبرغ',
                'city': 'جوهانسبرغ',
                'country': 'جنوب أفريقيا',
                'description': 'حفلة في مسرح جوهانسبرغ',
            },
            'حفلة لاغوس 2028': {
                'title_en': 'Lagos Concert 2028',
                'status': 'UPCOMING',
                'date': '2028-07-25 20:00',
                'venue_name': 'مسرح لاغوس',
                'city': 'لاغوس',
                'country': 'نيجيريا',
                'description': 'حفلة في مسرح لاغوس',
            },
            'حفلة نيروبي 2028': {
                'title_en': 'Nairobi Concert 2028',
                'status': 'UPCOMING',
                'date': '2028-08-30 20:00',
                'venue_name': 'مسرح نيروبي',
                'city': 'نيروبي',
                'country': 'كينيا',
                'description': 'حفلة في مسرح نيروبي',
            },
            'حفلة القاهرة 2028': {
                'title_en': 'Cairo Concert 2028',
                'status': 'UPCOMING',
                'date': '2028-10-05 21:00',
                'venue_name': 'ستاد القاهرة الدولي',
                'city': 'القاهرة',
                'country': 'مصر',
                'description': 'حفلة كبرى في ستاد القاهرة الدولي',
            },
            'دور عرض السينما - القاهرة - جالاكسي': {
                'title_en': 'Cinema Tour - Cairo - Galaxy',
                'status': 'UPCOMING',
                'date': '2026-10-10 21:00',
                'venue_name': 'سينما جالاكسي',
                'city': 'القاهرة',
                'country': 'مصر',
                'description': 'عرض سينمائي في سينما جالاكسي - القاهرة',
            },
            'دور عرض السينما - القاهرة - راديو سينما': {
                'title_en': 'Cinema Tour - Cairo - Radio Cinema',
                'status': 'UPCOMING',
                'date': '2026-10-17 21:00',
                'venue_name': 'راديو سينما',
                'city': 'القاهرة',
                'country': 'مصر',
                'description': 'عرض سينمائي في راديو سينما - القاهرة',
            },
            'دور عرض السينما - الجيزة - سينما فيستيفال': {
                'title_en': 'Cinema Tour - Giza - Festival Cinema',
                'status': 'UPCOMING',
                'date': '2026-10-24 21:00',
                'venue_name': 'سينما فيستيفال',
                'city': 'الجيزة',
                'country': 'مصر',
                'description': 'عرض سينمائي في سينما فيستيفال - الجيزة',
            },
            'دور عرض السينما - الجيزة - سينما أوربت': {
                'title_en': 'Cinema Tour - Giza - Orbit Cinema',
                'status': 'UPCOMING',
                'date': '2026-10-31 21:00',
                'venue_name': 'سينما أوربت',
                'city': 'الجيزة',
                'country': 'مصر',
                'description': 'عرض سينمائي في سينما أوربت - الجيزة',
            },
            'دور عرض السينما - الإسكندرية - سينما ايمر': {
                'title_en': 'Cinema Tour - Alexandria - Amer Cinema',
                'status': 'UPCOMING',
                'date': '2026-11-07 21:00',
                'venue_name': 'سينما ايمر',
                'city': 'الإسكندرية',
                'country': 'مصر',
                'description': 'عرض سينمائي في سينما ايمر - الإسكندرية',
            },
            'دور عرض السينما - الإسكندرية - سان استيفنو': {
                'title_en': 'Cinema Tour - Alexandria - San Stefano',
                'status': 'UPCOMING',
                'date': '2026-11-14 21:00',
                'venue_name': 'سان استيفنو',
                'city': 'الإسكندرية',
                'country': 'مصر',
                'description': 'عرض سينمائي في سان استيفنو - الإسكندرية',
            },
            'دور عرض السينما - الإسكندرية - سينما رويال': {
                'title_en': 'Cinema Tour - Alexandria - Royal Cinema',
                'status': 'UPCOMING',
                'date': '2026-11-21 21:00',
                'venue_name': 'سينما رويال',
                'city': 'الإسكندرية',
                'country': 'مصر',
                'description': 'عرض سينمائي في سينما رويال - الإسكندرية',
            },
        }

        created_concerts = 0
        skipped_concerts = 0

        for title_ar, concert_data in concerts_data.items():
            # Check if concert already exists
            existing = Concert.objects.filter(title_ar=title_ar).first()
            
            if existing:
                self.stdout.write(self.style.WARNING(f'Concert already exists: {title_ar}'))
                skipped_concerts += 1
                continue

            # Create concert
            concert = Concert.objects.create(
                title_ar=title_ar,
                title_en=concert_data['title_en'],
                status=concert_data['status'],
                date=concert_data['date'],
                venue_name=concert_data['venue_name'],
                city=concert_data['city'],
                country=concert_data['country'],
                description=concert_data['description'],
                organizer=organizer,
                visibility='PUBLISHED',
            )
            
            created_concerts += 1
            self.stdout.write(self.style.SUCCESS(f'Created concert: {title_ar}'))

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully created {created_concerts} concerts. '
                f'Skipped {skipped_concerts} already existing.'
            )
        )
