# Generated by Django 6.1 on 2026-08-28 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Model Name')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('model_type', models.CharField(max_length=100, verbose_name='Model Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('model_path', models.CharField(max_length=500, verbose_name='Model Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Source Name')),
                ('audio_file', models.FileField(upload_to='ai_remix/sources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac', 'm4a', 'ogg'])], verbose_name='Audio File')),
                ('source_type', models.CharField(choices=[('VOCAL', 'Vocal Track'), ('INSTRUMENTAL', 'Instrumental'), ('DRUMS', 'Drums'), ('BASS', 'Bass'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Source Type')),
                ('bpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM')),
                ('key', models.CharField(blank=True, max_length=10, verbose_name='Musical Key')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Audio Source',
                'verbose_name_plural': 'Audio Sources',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RemixProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('target_bpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Target BPM')),
                ('target_key', models.CharField(blank=True, max_length=10, verbose_name='Target Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Remix Project',
                'verbose_name_plural': 'Remix Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemixOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.FileField(upload_to='ai_remix/outputs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac'])], verbose_name='Output File')),
                ('format', models.CharField(default='mp3', max_length=10, verbose_name='Format')),
                ('bitrate', models.CharField(default='320k', max_length=10, verbose_name='Bitrate')),
                ('sample_rate', models.PositiveIntegerField(default=44100, verbose_name='Sample Rate')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='ai_remix_app.remixproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Remix Output',
                'verbose_name_plural': 'Remix Outputs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemixSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=1.0, verbose_name='Volume')),
                ('start_time', models.FloatField(default=0.0, verbose_name='Start Time (seconds)')),
                ('end_time', models.FloatField(blank=True, null=True, verbose_name='End Time (seconds)')),
                ('is_loop', models.BooleanField(default=False, verbose_name='Loop')),
                ('fade_in', models.FloatField(default=0.0, verbose_name='Fade In (seconds)')),
                ('fade_out', models.FloatField(default=0.0, verbose_name='Fade Out (seconds)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('audio_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remix_projects', to='ai_remix_app.audiosource', verbose_name='Audio Source')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='ai_remix_app.remixproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Remix Source',
                'verbose_name_plural': 'Remix Sources',
                'ordering': ['order'],
                'unique_together': {('project', 'audio_source')},
            },
        ),
    ]
