# Generated by Django 6.1 on 2026-09-03 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_remix_app', '0001_initial'),
        ('music_app', '0020_singwithtamerproject_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='remixproject',
            name='source_song_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='music_app.song'),
        ),
        migrations.AddField(
            model_name='remixproject',
            name='source_song_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='music_app.song'),
        ),
        migrations.AddIndex(
            model_name='remixproject',
            index=models.Index(fields=['source_song_1', 'source_song_2'], name='ai_remix_ap_source__505eee_idx'),
        ),
    ]
