# Generated by Django 6.1 on 2026-08-25 15:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ads/')),
                ('is_active', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('show_on_all_pages', models.BooleanField(default=True)),
                ('placements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'people_app'), ('model', 'person')), models.Q(('app_label', 'music_app'), ('model', 'album')), models.Q(('app_label', 'music_app'), ('model', 'song')), models.Q(('app_label', 'media_app'), ('model', 'media')), models.Q(('app_label', 'concerts_app'), ('model', 'concert')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_active'], name='ads_app_adv_is_acti_b6c612_idx'), models.Index(fields=['content_type', 'object_id'], name='ads_app_adv_content_f4f847_idx')],
            },
        ),
    ]
