# Generated by Django 6.1 on 2026-08-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('SPOTIFY', 'Spotify'), ('ANGHAMI', 'Anghami'), ('APPLE_MUSIC', 'Apple Music'), ('SHAHID', 'Shahid'), ('WATCH_IT', 'WATCH IT'), ('OTHER', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='links_app_e_content_fba1c0_idx')],
            },
        ),
    ]
