# Generated by Django 6.1 on 2026-08-25 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('SPOTIFY', 'Spotify'), ('ANGHAMI', 'Anghami'), ('APPLE_MUSIC', 'Apple Music'), ('NETFLIX', 'Netflix'), ('SHAHID', 'Shahid'), ('WATCH_IT', 'WATCH IT'), ('OTHER', 'Other')], max_length=20, unique=True)),
                ('logo_icon_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
            ],
            options={
                'ordering': ('platform_name',),
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('direct_url', models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('embed_code', models.TextField(blank=True)),
                ('access_type', models.CharField(choices=[('FREE', 'Free'), ('SUBSCRIPTION', 'Subscription'), ('RENTAL', 'Rental'), ('PURCHASE', 'Purchase')], default='FREE', max_length=15)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'music_app'), ('model', 'song')), models.Q(('app_label', 'media_app'), ('model', 'media')), models.Q(('app_label', 'concerts_app'), ('model', 'concert')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='links_app.platform')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='links_app_e_content_fba1c0_idx'), models.Index(fields=['platform'], name='links_app_e_platfor_283cf1_idx')],
            },
        ),
    ]
