# Generated by Django 6.1 on 2026-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube'), ('SPOTIFY', 'Spotify'), ('ANGHAMI', 'Anghami'), ('APPLE_MUSIC', 'Apple Music'), ('NETFLIX', 'Netflix'), ('SHAHID', 'Shahid'), ('WATCH_IT', 'WATCH IT'), ('OTHER', 'Other')], default='OTHER', max_length=20, unique=True),
        ),
    ]
