# Generated by Django 6.1 on 2026-08-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0003_alter_externallink_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube'), ('SPOTIFY', 'Spotify'), ('ANGHAMI', 'Anghami'), ('APPLE_MUSIC', 'Apple Music'), ('NETFLIX', 'Netflix'), ('SHAHID', 'Shahid'), ('WATCH_IT', 'WATCH IT'), ('TAZKARTI', 'Tazkarti'), ('TICKETMASTER', 'Ticketmaster'), ('OTHER', 'Other')], default='OTHER', max_length=20, unique=True),
        ),
    ]
