# Generated by Django 6.1 on 2026-09-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0004_alter_platform_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube'), ('SPOTIFY', 'Spotify'), ('ANGHAMI', 'Anghami'), ('APPLE_MUSIC', 'Apple Music'), ('DEEZER', 'Deezer'), ('AMAZON_MUSIC', 'Amazon Music'), ('SOUNDCLOUD', 'SoundCloud'), ('NETFLIX', 'Netflix'), ('SHAHID', 'Shahid'), ('WATCH_IT', 'WATCH IT'), ('YANGO_PLAY', 'Yango Play'), ('OSN_PLUS', 'OSN+'), ('AMAZON_PRIME', 'Amazon Prime Video'), ('DISNEY_PLUS', 'Disney+'), ('TAZKARTI', 'Tazkarti'), ('TICKETMASTER', 'Ticketmaster'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('OTHER', 'Other')], default='OTHER', max_length=20, unique=True),
        ),
    ]
