# Generated by Django 6.1 on 2026-09-19 03:23

import backend.links_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0006_alter_platform_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='direct_url',
            field=models.CharField(max_length=500, validators=[backend.links_app.models.validate_external_link_url]),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube'), ('SPOTIFY', 'Spotify'), ('ANGHAMI', 'Anghami'), ('APPLE_MUSIC', 'Apple Music'), ('DEEZER', 'Deezer'), ('AMAZON_MUSIC', 'Amazon Music'), ('SOUNDCLOUD', 'SoundCloud'), ('NETFLIX', 'Netflix'), ('SHAHID', 'Shahid'), ('WATCH_IT', 'WATCH IT'), ('YANGO_PLAY', 'Yango Play'), ('OSN_PLUS', 'OSN+'), ('AMAZON_PRIME', 'Amazon Prime Video'), ('DISNEY_PLUS', 'Disney+'), ('TAZKARTI', 'Tazkarti'), ('TICKETMASTER', 'Ticketmaster'), ('TICKETSMARCHE', 'Ticketsmarche'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('TWITTER', 'X (Twitter)'), ('SNAPCHAT', 'Snapchat'), ('LINKEDIN', 'LinkedIn'), ('THREADS', 'Threads'), ('WEBSITE', 'Website'), ('EMAIL', 'Email'), ('OTHER', 'Other')], default='OTHER', max_length=20, unique=True),
        ),
    ]
