# Generated by Django 6.1 on 2026-08-25 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('media_type', models.CharField(choices=[('MOVIE', 'Movie'), ('TV_SERIES', 'TV Series'), ('COMMERCIAL', 'Commercial'), ('PROGRAM', 'Program / Show')], db_index=True, max_length=15)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('synopsis', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('advertiser_company', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('campaign_concept', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-release_date', 'title_ar'),
                'indexes': [models.Index(fields=['media_type'], name='media_app_m_media_t_a8679b_idx'), models.Index(fields=['release_date'], name='media_app_m_release_32af77_idx'), models.Index(fields=['slug'], name='media_app_m_slug_cfd938_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DIRECTOR', 'Director'), ('PRODUCER', 'Producer'), ('SCREENWRITER', 'Screenwriter'), ('CINEMATOGRAPHER', 'Cinematographer'), ('COMPOSER', 'Composer'), ('ACTOR', 'Actor'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('character_name', models.CharField(blank=True, max_length=150)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='media_app.media')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_credits', to='people_app.person')),
            ],
            options={
                'unique_together': {('media', 'person', 'role', 'character_name')},
            },
        ),
    ]
