# Generated by Django 6.1 on 2026-08-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='When this becomes fully visible/open (used by Scheduled and Coming Soon).', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='visibility',
            field=models.CharField(choices=[('DRAFT', 'Hidden (draft)'), ('SCHEDULED', 'Scheduled'), ('COMING_SOON', 'Coming Soon'), ('PUBLISHED', 'Published')], db_index=True, default='PUBLISHED', max_length=15),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['visibility'], name='media_app_m_visibil_702a14_idx'),
        ),
    ]
