# Generated by Django 6.1 on 2026-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_media_publish_at_media_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('TV_SERIES', 'TV Series'), ('COMMERCIAL', 'Commercial'), ('PROGRAM', 'Program / Show')], db_index=True, default='MOVIE', max_length=15),
        ),
    ]
