# Generated by Django 6.1 on 2026-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_alter_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/posters/'),
        ),
    ]
