# Generated by Django 6.1 on 2026-08-26 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_media_poster_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('booking_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='media_app.media')),
            ],
            options={
                'ordering': ('city', 'cinema_name'),
            },
        ),
    ]
