# Generated by Django 6.1 on 2026-08-26 06:08

import backend.links_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0006_cinemavenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='cover_video',
            field=models.FileField(blank=True, null=True, upload_to=backend.links_app.models._hero_video_upload_path),
        ),
        migrations.AddField(
            model_name='media',
            name='cover_video_url',
            field=models.URLField(blank=True, help_text='رابط فيديو يوتيوب (اختياري) يظهر كخلفية الصفحة بدل الصورة.', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
