# Generated by Django 6.1 on 2026-08-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0007_media_cover_video_media_cover_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='cover_video_url',
        ),
    ]
