# Generated by Django 6.1 on 2026-08-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('links_app', '0002_alter_platform_platform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VIEW', 'Page View'), ('PLAY', 'Play'), ('SHARE', 'Share'), ('EXTERNAL_CLICK', 'External Platform Click')], db_index=True, max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('share_channel', models.CharField(blank=True, choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'X / Twitter'), ('TELEGRAM', 'Telegram'), ('COPY_LINK', 'Copy Link'), ('OTHER', 'Other')], max_length=15)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'people_app'), ('model', 'person')), models.Q(('app_label', 'music_app'), ('model', 'album')), models.Q(('app_label', 'music_app'), ('model', 'song')), models.Q(('app_label', 'media_app'), ('model', 'media')), models.Q(('app_label', 'concerts_app'), ('model', 'concert')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('external_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='links_app.externallink')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='links_app.platform')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'content_type', 'object_id'], name='analytics_a_event_t_0f3964_idx'), models.Index(fields=['created_at'], name='analytics_a_created_08c04f_idx')],
            },
        ),
    ]
