# Generated by Django 6.1 on 2026-08-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_alter_analyticsevent_content_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'people_app'), ('model', 'person')), models.Q(('app_label', 'studios_app'), ('model', 'studio')), models.Q(('app_label', 'music_app'), ('model', 'album')), models.Q(('app_label', 'music_app'), ('model', 'song')), models.Q(('app_label', 'media_app'), ('model', 'media')), models.Q(('app_label', 'concerts_app'), ('model', 'concert')), models.Q(('app_label', 'ads_app'), ('model', 'advertisement')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
