# Generated by Django 6.1 on 2026-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ar', models.CharField(max_length=200)),
                ('full_name_en', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('primary_role', models.CharField(choices=[('SINGER', 'Singer'), ('POET', 'Poet / Lyricist'), ('COMPOSER', 'Composer'), ('ARRANGER', 'Arranger'), ('MUSIC_PRODUCER', 'Music Producer'), ('RECORDING_ENGINEER', 'Recording Engineer'), ('MIX_MASTER_ENGINEER', 'Mix & Master Engineer'), ('DIRECTOR', 'Director'), ('PRODUCER', 'Producer'), ('SCREENWRITER', 'Screenwriter'), ('CINEMATOGRAPHER', 'Cinematographer'), ('ACTOR', 'Actor'), ('CO_ARTIST', 'Co-Artist / Featured Artist'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='people/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('full_name_ar',),
                'indexes': [models.Index(fields=['primary_role'], name='people_app__primary_01950f_idx'), models.Index(fields=['slug'], name='people_app__slug_d18310_idx')],
            },
        ),
    ]
