# Generated by Django 6.1 on 2026-08-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0002_alter_person_primary_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='primary_role',
            field=models.CharField(choices=[('SINGER', 'Singer'), ('POET', 'Poet / Lyricist'), ('COMPOSER', 'Composer'), ('ARRANGER', 'Arranger'), ('MUSIC_PRODUCER', 'Music Producer'), ('RECORDING_ENGINEER', 'Recording Engineer'), ('MIXING_ENGINEER', 'Mixing Engineer'), ('MASTERING_ENGINEER', 'Mastering Engineer'), ('MIX_MASTER_ENGINEER', 'Mix & Master Engineer'), ('DIRECTOR', 'Director'), ('PRODUCER', 'Producer'), ('SCREENWRITER', 'Screenwriter'), ('CINEMATOGRAPHER', 'Cinematographer'), ('ACTOR', 'Actor'), ('CO_ARTIST', 'Co-Artist / Featured Artist'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30),
        ),
    ]
