# Generated by Django 6.1 on 2026-08-29 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main_app', '0003_favorite_playlist_playlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'مفضل', 'verbose_name_plural': 'المفضلة'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['song', 'media', 'concert']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='main_app_fa_user_id_a2f066_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['created_at'], name='main_app_fa_created_fa9f1b_idx'),
        ),
    ]
