# Generated by Django 6.1 on 2026-08-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main_app', '0004_alter_favorite_options_alter_favorite_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'إعجاب',
                'verbose_name_plural': 'الإعجاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='main_app_fa_user_id_a2f066_idx',
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='main_app_fa_created_fa9f1b_idx',
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['song', 'media', 'concert']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='main_app_li_user_id_1e4871_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['created_at'], name='main_app_li_created_5cb879_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
