# Generated by Django 6.1 on 2026-08-29 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_like_alter_favorite_unique_together_and_more'),
        ('music_app', '0012_song_play_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSongPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_played_at', models.DateTimeField(auto_now=True, verbose_name='آخر تشغيل')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات التشغيل للمستخدم')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plays', to='music_app.song', verbose_name='الأغنية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_plays', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تشغيل مستخدم',
                'verbose_name_plural': 'تشغيلات المستخدمين',
                'ordering': ['-last_played_at'],
                'indexes': [models.Index(fields=['user', 'song'], name='main_app_us_user_id_cc5e36_idx'), models.Index(fields=['last_played_at'], name='main_app_us_last_pl_072cd8_idx')],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
