# Generated by Django 6.1 on 2026-08-29 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_usersongplay'),
        ('music_app', '0012_song_play_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSongListener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, verbose_name='آخر نبض')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_listeners', to='music_app.song', verbose_name='الأغنية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_listening', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مستخدم حالي',
                'verbose_name_plural': 'المستخدمون الحاليون',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'song'], name='main_app_cu_user_id_5fd9ce_idx'), models.Index(fields=['song'], name='main_app_cu_song_id_38861a_idx'), models.Index(fields=['last_heartbeat'], name='main_app_cu_last_he_84c252_idx')],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
