# Generated by Django 6.1 on 2026-09-01 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_currentsonglistener'),
        ('music_app', '0015_songlyricsegment_double_tracking_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currentsonglistener',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='currentsonglistener',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مفتاح الجلسة'),
        ),
        migrations.AlterField(
            model_name='currentsonglistener',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_listening', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddConstraint(
            model_name='currentsonglistener',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'song'), name='unique_user_song'),
        ),
        migrations.AddConstraint(
            model_name='currentsonglistener',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('session_key', 'song'), name='unique_session_song'),
        ),
    ]
