# Generated by Django 6.1 on 2026-09-03 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_currentsonglistener_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='الكود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'كود استعادة كلمة السر',
                'verbose_name_plural': 'أكواد استعادة كلمة السر',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'code'], name='main_app_pa_user_id_97e80e_idx')],
            },
        ),
    ]
