# Generated by Django 6.1 on 2026-09-03 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_passwordresetcode'),
        ('music_app', '0020_singwithtamerproject_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersongplay',
            name='decayed_score',
            field=models.FloatField(default=0.0, verbose_name='نقاط التفاعل (متناقصة زمنياً)'),
        ),
        migrations.AddField(
            model_name='usersongplay',
            name='full_listen_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستماع الكامل'),
        ),
        migrations.AddField(
            model_name='usersongplay',
            name='score_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث للنقاط'),
        ),
        migrations.CreateModel(
            name='SongLeaderboardRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('full_listen_count', models.PositiveIntegerField(default=0)),
                ('is_liked', models.BooleanField(default=False)),
                ('trend', models.CharField(choices=[('UP', 'صاعد'), ('DOWN', 'هابط'), ('SAME', 'ثابت'), ('NEW', 'جديد')], default='NEW', max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_ranks', to='music_app.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_leaderboard_ranks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['song', 'rank'], name='main_app_so_song_id_a0f92c_idx')],
                'unique_together': {('song', 'user')},
            },
        ),
    ]
