# Generated by Django 6.1 on 2026-09-08 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_pushsubscription'),
        ('music_app', '0028_dailyguessattempt_listening_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('method', models.CharField(choices=[('COLLABORATIVE', 'تعاوني (حسب المستمعين)'), ('CONTENT', 'حسب المحتوى')], max_length=15)),
                ('rank', models.PositiveSmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similar_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='music_app.song')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='music_app.song')),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['song', 'rank'], name='main_app_so_song_id_7d2260_idx')],
                'unique_together': {('song', 'similar_song')},
            },
        ),
        migrations.CreateModel(
            name='UserSongRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('rank', models.PositiveSmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='music_app.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['user', 'rank'], name='main_app_us_user_id_4c642f_idx')],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
