# Generated by Django 6.1 on 2026-09-08 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_songsimilarity_usersongrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMoodScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('ROMANTIC', 'Romantic / رومانسي'), ('SAD_HEARTBREAK', 'Sad & Heartbreak / حزين / دراما / جرح'), ('ENERGETIC_UPBEAT', 'Energetic & Upbeat / حماسي / طاقة عالية / أفراح'), ('MOTIVATIONAL_HOPEFUL', 'Motivational & Hopeful / تحفيزي / أمل وتفاؤل'), ('CHILL_RELAXING', 'Chill & Relaxing / رايق / هادئ للاسترخاء'), ('NOSTALGIC', 'Nostalgic / ذكريات وحنين'), ('CONFIDENT_PLAYFUL', 'Confident & Playful / واثق / فريش')], max_length=25)),
                ('decayed_score', models.FloatField(default=0.0)),
                ('score_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'mood'], name='main_app_us_user_id_89fdb5_idx')],
                'unique_together': {('user', 'mood')},
            },
        ),
    ]
