# Generated by Django 6.1 on 2026-09-08 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_usermoodscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAssistantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_session_id', models.CharField(blank=True, max_length=32)),
                ('event_type', models.CharField(choices=[('RECOGNITION_START', 'Recognition session started'), ('RECOGNITION_END', 'Recognition session ended'), ('RECOGNITION_ERROR', 'Recognition error event'), ('START_EXCEPTION', 'recognition.start() threw synchronously'), ('WATCHDOG_RESTART', 'Watchdog forced a restart'), ('WAKE_DETECTED', 'Wake word detected'), ('COMMAND_MATCHED', 'Command matched a local pattern'), ('COMMAND_IGNORED_GRACE', 'Ignored as post-arm restart noise'), ('COMMAND_AI_FALLBACK', 'Sent to the AI intent fallback'), ('COMMAND_FAILED', 'No match found anywhere')], max_length=32)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('transcript', models.CharField(blank=True, max_length=300)),
                ('ms_value', models.IntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_assistant_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['client_session_id', 'created_at'], name='main_app_vo_client__545c23_idx')],
            },
        ),
    ]
