# Generated by Django 6.1 on 2026-09-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_voiceassistantlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceassistantlog',
            name='event_type',
            field=models.CharField(choices=[('RECOGNITION_START', 'Recognition session started'), ('RECOGNITION_END', 'Recognition session ended'), ('RECOGNITION_ERROR', 'Recognition error event'), ('START_EXCEPTION', 'recognition.start() threw synchronously'), ('WATCHDOG_RESTART', 'Watchdog forced a restart'), ('WAKE_DETECTED', 'Wake word detected'), ('COMMAND_MATCHED', 'Command matched a local pattern'), ('COMMAND_IGNORED_GRACE', 'Ignored as post-arm restart noise'), ('COMMAND_AI_FALLBACK', 'Sent to the AI intent fallback'), ('COMMAND_FAILED', 'No match found anywhere'), ('NETWORK_TOO_WEAK', 'Skipped engaging the mic - network too weak')], max_length=32),
        ),
    ]
