# Generated by Django 6.1 on 2026-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_voiceassistantlog_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceKnownPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_transcript', models.CharField(max_length=300)),
                ('intent', models.CharField(max_length=32)),
                ('song_query', models.CharField(blank=True, max_length=200)),
                ('mood', models.CharField(blank=True, max_length=32)),
                ('page', models.CharField(blank=True, max_length=64)),
                ('paraphrases', models.JSONField(blank=True, default=list)),
                ('hit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
