# Generated by Django 6.1 on 2026-09-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_voiceknownphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceknownphrase',
            name='lyrics_query',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
