# Generated by Django 6.1 on 2026-09-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_add_command_no_result_event_type'),
        ('music_app', '0029_add_full_song_segment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongTrendingRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('previous_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('trend', models.CharField(choices=[('UP', 'صاعد'), ('DOWN', 'هابط'), ('SAME', 'ثابت'), ('NEW', 'جديد')], default='NEW', max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending_rank', to='music_app.song')),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['rank'], name='main_app_so_rank_241ab3_idx')],
            },
        ),
    ]
