# Generated by Django 6.1 on 2026-09-20 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_songtrendingrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenTogetherBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المنع')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_together_blocks_received', to=settings.AUTH_USER_MODEL, verbose_name='الممنوع')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_together_blocks_made', to=settings.AUTH_USER_MODEL, verbose_name='المانع')),
            ],
            options={
                'verbose_name': 'منع اسمع معاه',
                'verbose_name_plural': 'ممنوعو اسمع معاه',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked'], name='main_app_li_blocker_45b396_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
