# Generated by Django 6.1 on 2026-09-20 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_listentogetherblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenTogetherRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=60, verbose_name='اسم الجروب')),
                ('generated_name', models.CharField(blank=True, max_length=60, verbose_name='اسم مولّد')),
                ('is_public', models.BooleanField(default=True, verbose_name='عام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listen_together_room', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الجروب')),
            ],
            options={
                'verbose_name': 'جروب اسمع معاه',
                'verbose_name_plural': 'جروبات اسمع معاه',
            },
        ),
        migrations.CreateModel(
            name='ListenTogetherJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_together_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='main_app.listentogetherroom', verbose_name='الجروب')),
            ],
            options={
                'verbose_name': 'طلب انضمام',
                'verbose_name_plural': 'طلبات الانضمام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listentogetherroom',
            index=models.Index(fields=['is_public'], name='main_app_li_is_publ_5a242e_idx'),
        ),
        migrations.AddIndex(
            model_name='listentogetherjoinrequest',
            index=models.Index(fields=['room', 'status'], name='main_app_li_room_id_da413f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listentogetherjoinrequest',
            unique_together={('room', 'requester')},
        ),
    ]
