# Generated by Django 6.1 on 2026-09-20 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_listentogetherroom_listentogetherjoinrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentogetherroom',
            name='tap_score',
            field=models.PositiveIntegerField(default=0, verbose_name='نقاط التكبيس'),
        ),
        migrations.CreateModel(
            name='ListenTogetherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('message', 'رسالة'), ('system', 'نظام')], default='message', max_length=10, verbose_name='النوع')),
                ('text', models.CharField(max_length=300, verbose_name='النص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listen_together_comments', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.listentogetherroom', verbose_name='الجروب')),
            ],
            options={
                'verbose_name': 'تعليق اسمع معاه',
                'verbose_name_plural': 'تعليقات اسمع معاه',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='main_app_li_room_id_cce637_idx')],
            },
        ),
    ]
