# Generated by Django 6.1 on 2026-09-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_listentogetherroom_tap_score_listentogethercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentogetherroom',
            name='is_live',
            field=models.BooleanField(default=True, verbose_name='شغال دلوقتي'),
        ),
        migrations.AddIndex(
            model_name='listentogetherroom',
            index=models.Index(fields=['is_live'], name='main_app_li_is_live_ae79aa_idx'),
        ),
    ]
