# Generated by Django 6.1 on 2026-09-21 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_listentogetherroom_is_live_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenTogetherTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='عدد الكبسات')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taps', to='main_app.listentogetherroom', verbose_name='الجروب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_together_taps', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'كبسة اسمع معاه',
                'verbose_name_plural': 'كبسات اسمع معاه',
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_room_tap_user')],
            },
        ),
    ]
