# Generated by Django 6.1 on 2026-09-21 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_listentogethertap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenTogetherViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الدخول')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='main_app.listentogetherroom', verbose_name='الجروب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_together_viewing', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'متابع اسمع معاه',
                'verbose_name_plural': 'متابعين اسمع معاه',
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_room_viewer_user')],
            },
        ),
    ]
