# Generated by Django 6.1 on 2026-09-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_listentogetherviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listentogetherjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('expired', 'انتهت المهلة')], default='pending', max_length=10, verbose_name='الحالة'),
        ),
    ]
