# Generated by Django 6.1 on 2026-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_alter_listentogetherjoinrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentogetherviewer',
            name='last_heartbeat',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر نبض'),
        ),
        migrations.AddIndex(
            model_name='listentogetherviewer',
            index=models.Index(fields=['last_heartbeat'], name='main_app_li_last_he_d50369_idx'),
        ),
    ]
