# Generated by Django 6.1 on 2026-09-24 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_listentogetherviewer_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_participants', models.PositiveSmallIntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8'), (12, '12')], default=4, verbose_name='أقصى عدد أشخاص')),
                ('is_live', models.BooleanField(default=True, verbose_name='شغالة دلوقتي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_room', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الروم')),
            ],
            options={
                'verbose_name': 'روم صوتية',
                'verbose_name_plural': 'رومات صوتية',
            },
        ),
        migrations.CreateModel(
            name='AudioRoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField(verbose_name='رقم المقعد')),
                ('is_muted', models.BooleanField(default=False, verbose_name='مكتوم')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الدخول')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main_app.audioroom', verbose_name='الروم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_room_participations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مشارك روم صوتية',
                'verbose_name_plural': 'مشاركين روم صوتية',
            },
        ),
        migrations.AddIndex(
            model_name='audioroom',
            index=models.Index(fields=['is_live'], name='main_app_au_is_live_aa0166_idx'),
        ),
        migrations.AddConstraint(
            model_name='audioroomparticipant',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_audio_room_user'),
        ),
        migrations.AddConstraint(
            model_name='audioroomparticipant',
            constraint=models.UniqueConstraint(fields=('room', 'slot_index'), name='unique_audio_room_slot'),
        ),
    ]
