# Generated by Django 6.1 on 2026-09-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_audioroom_audioroomparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioroom',
            name='max_participants',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (6, '6'), (8, '8'), (12, '12')], default=4, verbose_name='أقصى عدد أشخاص'),
        ),
    ]
