# Generated by Django 6.1 on 2026-09-24 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_alter_audioroom_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioroom',
            name='custom_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='اسم الروم'),
        ),
        migrations.AddField(
            model_name='audioroom',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='عامة'),
        ),
        migrations.AddField(
            model_name='audioroom',
            name='tap_score',
            field=models.PositiveIntegerField(default=0, verbose_name='نقاط التكبيس'),
        ),
        migrations.CreateModel(
            name='AudioRoomComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('message', 'رسالة'), ('system', 'نظام')], default='message', max_length=10, verbose_name='النوع')),
                ('text', models.CharField(max_length=300, verbose_name='النص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_room_comments', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.audioroom', verbose_name='الروم')),
            ],
            options={
                'verbose_name': 'تعليق روم صوتية',
                'verbose_name_plural': 'تعليقات روم صوتية',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='main_app_au_room_id_288f4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AudioRoomTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='عدد الكبسات')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taps', to='main_app.audioroom', verbose_name='الروم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_room_taps', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'كبسة روم صوتية',
                'verbose_name_plural': 'كبسات روم صوتية',
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_audio_room_tap_user')],
            },
        ),
    ]
