# Generated by Django 6.1 on 2026-09-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_audioroom_custom_name_audioroom_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='team_title',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='لقب فريق العمل (يظهر في الهوم بيج لو مش فاضي)'),
        ),
    ]
