# Generated by Django 6.1 on 2026-10-06 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_useraccount_team_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioroomparticipant',
            name='slot_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='رقم المقعد'),
        ),
        migrations.CreateModel(
            name='AudioRoomSeatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('request', 'طلب مقعد'), ('invite', 'دعوة')], max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests', to='main_app.audioroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_seat_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'user', 'is_resolved'], name='main_app_au_room_id_c8cfd2_idx')],
            },
        ),
    ]
