# Generated by Django 6.1 on 2026-10-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_audio_room_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioroom',
            name='host_channel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audioroom',
            name='host_left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
