# Generated by Django 6.1 on 2026-10-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_audio_room_host_grace'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioroomparticipant',
            name='is_host_muted',
            field=models.BooleanField(default=False),
        ),
    ]
