# Generated by Django 6.1 on 2026-10-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_audio_participant_host_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentogetherroom',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
