# Generated by Django 6.1 on 2026-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('entity_type', models.CharField(choices=[('RECORDING_STUDIO', 'Recording Studio'), ('RECORD_LABEL', 'Record Label'), ('PRODUCTION_COMPANY', 'Production Company'), ('DISTRIBUTION', 'Distribution')], db_index=True, max_length=25)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='studios/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['entity_type'], name='studios_app_entity__87a915_idx')],
            },
        ),
    ]
