# Generated by Django 6.1 on 2026-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='entity_type',
            field=models.CharField(choices=[('RECORDING_STUDIO', 'Recording Studio'), ('RECORD_LABEL', 'Record Label'), ('PRODUCTION_COMPANY', 'Production Company'), ('DISTRIBUTION', 'Distribution')], db_index=True, default='RECORDING_STUDIO', max_length=25),
        ),
    ]
